# Redirects for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"